def standardize_editor_column_names(columns):
    column_mapper = {'Status':'STAT',
                 'Last Updated': 'LAST_UPDATE',
                 'Jurisdiction Status': 'JXTN_STAT',
                 'State': 'STATE',
                 'County': 'COUNTY',
                 'Jurisdiction': 'JXTN',
                 'Parent Jurisdiction': 'PARENT_JXTN',
                 'Abbreviated District Name': 'ABB_DIST_NAME',
                 'Full District Name': 'DIST_NAME',
                 'Effective Start Date': 'BYLAW_EFF',
                 'Changed or Expired': 'CHANGE_EXP',
                 'District Mapped But Extinct': 'EXT_DIST',
                 'Overlay': 'OVER',
                 'Type of Zoning District': 'DIST_TYPE',
                 'Affordable Housing District': 'AFF_DIST',
                 'Elderly Housing District': 'ELD_DIST',
                 '1-Family Treatment': '1FDP',
                 '2-Family Treatment': '2FDP',
                 '3-Family Treatment': '3FDP',
                 '4+-Family Treatment': '4FDP',
                 '1-Family Min. Lot': '1F_MIN_LOT',
                 '1-Family Min. Lot Units': '1F_MIN_LOT_UNITS',
                 '1-Family Front Setback': '1F_FSET',
                 '1-Family Front Setback Units': '1F_FSET_UNITS',
                 '1-Family Side Setback': '1F_SSET',
                 '1-Family Side Setback Units': '1F_SSET_UNITS',
                 '1-Family Rear Setback': '1F_RSET',
                 '1-Family Rear Setback Units': '1F_RSET_UNITS',
                 '1-Family Max. Lot Coverage - Buildings': '1F_MAX_LOT_BLDG',
                 '1-Family Max. Lot Coverage - Buildings Units': '1F_MAX_LOT_BLDG_UNITS',
                 '1-Family Max. Lot Coverage - Buildings & Impervious Surface': '1F_MAX_LOT_IMP',
                 '1-Family Max. Lot Coverage - Buildings & Impervious Surface Units': '1F_MAX_LOT_IMP_UNITS',
                 '1-Family Min. # Parking Spaces': '1F_PARK',
                 '1-Family Min. # Parking Spaces Units': '1F_PARK_UNITS',
                 '1-Family Max. Stories': '1F_STORIES',
                 '1-Family Max. Stories Units': '1F_STORIES_UNITS',
                 '1-Family Max. Height': '1F_HEIGHT',
                 '1-Family Max. Height Units': '1F_HEIGHT_UNITS',
                 '1-Family Floor to Area Ratio': '1F_FTA',
                 '1-Family Floor to Area Ratio Units': '1F_FTA_UNITS',
                 '1-Family Min. Unit Size': '1F_MIN_UNIT',
                 '1-Family Min. Unit Size Units': '1F_MIN_UNIT_UNITS',
                 '2-Family Affordable Housing Only': '2F_AFF',
                 '2-Family Elderly Housing Only': '2F_ELD',
                 '2-Family Min. Lot': '2F_MIN_LOT',
                 '2-Family Min. Lot Units': '2F_MIN_LOT_UNITS',
                 '2-Family Max. Density': '2F_MAX_DENS',
                 '2-Family Max. Density Units': '2F_MAX_DENS_UNITS',
                 '2-Family Front Setback': '2F_FSET',
                 '2-Family Front Setback Units': '2F_FSET_UNITS',
                 '2-Family Side Setback': '2F_SSET',
                 '2-Family Side Setback Units': '2F_SSET_UNITS',
                 '2-Family Rear Setback': '2F_RSET',
                 '2-Family Rear Setback Units': '2F_RSET_UNITS',
                 '2-Family Max. Lot Coverage - Buildings': '2F_MAX_LOT_BLDG',
                 '2-Family Max. Lot Coverage - Buildings Units' : '2F_MAX_LOT_BLDG_UNITS',
                 '2-Family Max. Lot Coverage - Buildings & Impervious Surface': '2F_MAX_LOT_IMP',
                 '2-Family Max. Lot Coverage - Buildings & Impervious Surface Units': '2F_MAX_LOT_IMP_UNITS',
                 '2-Family Min. # Parking Spaces Per Studio or 1BR': '2F_PARK_1BR',
                 '2-Family Min. # Parking Spaces Per Studio or 1BR Units': '2F_PARK_1BR_UNITS',
                 '2-Family Min. # Parking Spaces Per 2+ BR': '2F_PARK_2BR',
                 '2-Family Min. # Parking Spaces Per 2+ BR Units': '2F_PARK_2BR_UNITS',
                 '2-Family Max. Stories': '2F_STORIES',
                 '2-Family Max. Stories Units': '2F_STORIES_UNITS',
                 '2-Family Max. Height': '2F_HEIGHT',
                 '2-Family Max. Height Units': '2F_HEIGHT_UNITS',
                 '2-Family Floor to Area Ratio': '2F_FTA',
                 '2-Family Floor to Area Ratio Units': '2F_FTA_UNITS',
                 '2-Family Min. Unit Size': '2F_MIN_UNIT',
                 '2-Family Min. Unit Size Units': '2F_MIN_UNIT_UNITS',
                 '3-Family Affordable Housing Only': '3F_AFF',
                 '3-Family Elderly Housing Only': '3F_ELD',
                 '3-Family Min. Lot': '3F_MIN_LOT',
                 '3-Family Min. Lot Units': '3F_MIN_LOT_UNITS',
                 '3-Family Max. Density': '3F_MAX_DENS',
                 '3-Family Max. Density Units': '3F_MAX_DENS_UNITS',
                 '3-Family Front Setback': '3F_FSET',
                 '3-Family Front Setback Units': '3F_FSET_UNITS',
                 '3-Family Side Setback': '3F_SSET',
                 '3-Family Side Setback Units': '3F_SSET_UNITS',
                 '3-Family Rear Setback': '3F_RSET',
                 '3-Family Rear Setback Units': '3F_RSET_UNITS',
                 '3-Family Max. Lot Coverage - Buildings': '3F_MAX_LOT_BLDG',
                 '3-Family Max. Lot Coverage - Buildings Units' : '3F_MAX_LOT_BLDG_UNITS',
                 '3-Family Max. Lot Coverage - Buildings & Impervious Surface': '3F_MAX_LOT_IMP',
                 '3-Family Max. Lot Coverage - Buildings & Impervious Surface Units': '3F_MAX_LOT_IMP_UNITS',
                 '3-Family Min. # Parking Spaces Per Studio or 1BR': '3F_PARK_1BR',
                 '3-Family Min. # Parking Spaces Per Studio or 1BR Units': '3F_PARK_1BR_UNITS',
                 '3-Family Min. # Parking Spaces Per 2+ BR': '3F_PARK_2BR',
                 '3-Family Min. # Parking Spaces Per 2+ BR Units': '3F_PARK_2BR_UNITS',
                 '3-Family Connection to Sewer and/or Water Required': '3F_CNXN_H2O',
                 '3-Family Connection or Proximity to Public Transit Required': '3F_CNXN_TRANSIT',
                 '3-Family Max. Stories': '3F_STORIES',
                 '3-Family Max. Stories Units': '3F_STORIES_UNITS',
                 '3-Family Max. Height': '3F_HEIGHT',
                 '3-Family Max. Height Units': '3F_HEIGHT_UNITS',
                 '3-Family Floor to Area Ratio': '3F_FTA',
                 '3-Family Floor to Area Ratio Units': '3F_FTA_UNITS',
                 '3-Family Min. Unit Size': '3F_MIN_UNIT',
                 '3-Family Min. Unit Size Units': '3F_MIN_UNIT_UNITS',
                 '3-Family Max. Bedrooms Per Unit': '3F_BEDROOMS',
                 '3-Family Max. Bedrooms Per Unit Units': '3F_BEDROOMS_UNITS',
                 '4+-Family Affordable Housing Only': '4F_AFF',
                 '4+-Family Elderly Housing Only': '4F_ELD',
                 '4+-Family Min. Lot': '4F_MIN_LOT',
                 '4+-Family Min. Lot Units': '4F_MIN_LOT_UNITS',
                 '4+-Family Max. Density': '4F_MAX_DENS',
                 '4+-Family Max. Density Units': '4F_MAX_DENS_UNITS',
                 '4+-Family Front Setback': '4F_FSET',
                 '4+-Family Front Setback Units': '4F_FSET_UNITS',
                 '4+-Family Side Setback': '4F_SSET',
                 '4+-Family Side Setback Units': '4F_SSET_UNITS',
                 '4+-Family Rear Setback': '4F_RSET',
                 '4+-Family Rear Setback Units': '4F_RSET_UNITS',
                 '4+-Family Max. Lot Coverage - Buildings': '4F_MAX_LOT_BLDG',
                 '4+-Family Max. Lot Coverage - Buildings Units': '4F_MAX_LOT_BLDG_UNITS',
                 '4+-Family Max. Lot Coverage - Buildings & Impervious Surface': '4F_MAX_LOT_IMP',
                 '4+-Family Max. Lot Coverage - Buildings & Impervious Surface Units': '4F_MAX_LOT_IMP_UNITS',
                 '4+-Family Min. # Parking Spaces Per Studio or 1BR': '4F_PARK_1BR',
                 '4+-Family Min. # Parking Spaces Per Studio or 1BR Units': '4F_PARK_1BR_UNITS',
                 '4+-Family Min. # Parking Spaces Per 2+ BR': '4F_PARK_2BR',
                 '4+-Family Min. # Parking Spaces Per 2+ BR Units': '4F_PARK_2BR_UNITS',
                 '4+-Family Connection to Sewer and/or Water Required': '4F_CNXN_H2O',
                 '4+-Family Connection or Proximity to Public Transit Required': '4F_CNXN_TRANSIT',
                 '4+-Family Max. Stories': '4F_STORIES',
                 '4+-Family Max. Stories Units': '4F_STORIES_UNITS',
                 '4+-Family Max. Height': '4F_HEIGHT',
                 '4+-Family Max. Height Units': '4F_HEIGHT_UNITS',
                 '4+-Family Floor to Area Ratio': '4F_FTA',
                 '4+-Family Floor to Area Ratio Units': '4F_FTA_UNITS',
                 '4+-Family Min. Unit Size': '4F_MIN_UNIT',
                 '4+-Family Min. Unit Size Units': '4F_MIN_UNIT_UNITS',
                 '4+-Family Max. Bedrooms': '4F_BEDROOMS',
                 '4+-Family Max. Bedrooms Units': '4F_BEDROOMS_UNITS',
                 '4+-Family Max. Units': '4F_MAX_UNITS',
                 '4+-Family Max. Units Units': '4F_MAX_UNITS_UNITS',
                 'Affordable Housing (AH) Treatment': 'AFFDP',
                 'AH - Definition': 'AFF_DEF',
                 'AH - Elderly Housing Only': 'AFF_ELD_ONLY',
                 'AH Min. Lot': 'AFF_MIN_LOT',
                 'AH Min. Lot Units': 'AFF_MIN_LOT_UNITS',
                 'AH Max. Density': 'AFF_MAX_DENS',
                 'AH Max. Density Units': 'AFF_MAX_DENS_UNITS',
                 'AH Min. Parking Spaces Per Studio or 1BR': 'AFF_PARK_1BR',
                 'AH Min. Parking Spaces Per Studio or 1BR Units': 'AFF_PARK_1BR_UNITS',
                 'AH Min. Parking Spaces Per 2+ BR': 'AFF_PARK_2BR',
                 'AH Min. Parking Spaces Per 2+ BR Units': 'AFF_PARK_2BR',
                 'AH Connection to Sewer and/or Water Required': 'AFF_CNXN_H2O',
                 'AH Connection or Proximity to Public Transit Required': 'AFF_CNXN_TRANSIT',
                 'AH Min. Unit Size': 'AFF_MIN_UNIT',
                 'AH Min. Unit Size Units': 'AFF_MIN_UNIT_UNITS',
                 'AH Max. Bedrooms': 'AFF_BEDROOMS',
                 'AH Max. Bedrooms Units': 'AFF_BEDROOMS_UNITS',
                 'AH Max. Units': 'AFF_MAX_UNITS',
                 'AH Max. Units Units': 'AFF_MAX_UNIT_UNITS',
                 'Accessory Dwelling Unit (ADU) Treatment': 'ADUDP',
                 'ADU Employee or Family Occupancy Required': 'ADU_EMP_REQD',
                 'ADU Renter Occupancy Prohibited': 'ADU_RENTER_PROH',
                 'ADU Owner Occupancy Required': 'ADU_OWNER_REQD',
                 'ADU Elderly Housing Only': 'ADU_ELD',
                 'ADU Min. Lot': 'ADU_MIN_LOT',
                 'ADU Min. Lot Units': 'ADU_MIN_LOT_UNITS',
                 'ADU Min. Parking Spaces': 'ADU_PARK',
                 'ADU Min. Parking Spaces Units': 'ADU_PARK_UNITS',
                 'ADU Restricted to Only Primary Structure (i.e., No Outbuildings like Garages)': 'ADU_PRIM_STRUC',
                 'ADU Max. Percent Main Unit': 'ADU_MAX_PCT',
                 'ADU Max. Percent Main Unit Units': 'ADU_MAX_PCT_UNITS',
                 'ADU Max. Size': 'ADU_MAX_SIZE',
                 'ADU Max. Size Units': 'ADU_MAX_SIZE_UNITS',
                 'ADU Max. Bedrooms': 'ADU_BEDROOMS',
                 'ADU Max. Bedrooms Units': 'ADU_BEDROOMS_UNITS',
                 'Planned Residential Development (PRD) Treatment': 'PRDDP',
                 'Mobile or Manufactured Home Park (Y/N)': 'PRD_MHP',
                 'PRD Min. Lot': 'PRD_MIN_LOT',
                 'PRD Min. Lot Units': 'PRD_MIN_LOT_UNITS',
                 'PRD Max. Density': 'PRD_MAX_DENS',
                 'PRD Max. Density Units': 'PRD_MAX_DENS_UNITS',
                 'PRD Max. Units': 'PRD_MAX_UNITS',
                 'PRD Max. Units Units': 'PRD_MAX_UNITS_UNITS',
                 'Special Notes': 'SPNOTES',
                 'Tooltip Notes': 'TTIPNOTES',
                 '5+Family Affordable Housing Only': '5F_AFF',
                 '5+Family Elderly Housing Only': '5F_ELD',
                 '5+Family Min. Lot (ACRES)': '5F_MIN_LOT',
                 '5+Family Max. Density (UNITS/ACRE)': '5F_MAX_DENS',
                 '5+Family Front Setback (# of feet)': '5F_FSET',
                 '5+Family Side Setback (# of feet)': '5F_SSET',
                 '5+Family Rear Setback (# of feet)': '5F_RSET',
                 '5+Family Max. Lot Coverage - Buildings (%)': '5F_MAX_LOT_BLDG',
                 '5+Family Max. Lot Coverage - Buildings & Imperviou': '5F_MAX_LOT_IMP',
                 '5+Family Min. # Parking Spaces Per Studio or 1BR': '5F_PARK_1BR',
                 '5+Family Min. # Parking Spaces Per 2+ BR': '5F_PARK_2BR',
                 '5+Family Connection to Sewer and/or Water Required': '5F_CNXN_H2O',
                 '5+Family Connection or Proximity to Public Transit': '5F_CNXN_TRANSIT',
                 '5+Family Max. Height (# of stories)': '5F_STORIES',
                 '5+Family Max. Height (# of feet)': '5F_FEET',
                 '5+Family Floor to Area Ratio': '5F_FTA',
                 '5+Family Min. Unit Size (SF)': '5F_MIN_UNIT',
                 '5+Family Max. # Bedrooms Per Unit': '5F_BEDROOMS',
                 '5+Family Max. # Units Per Building': '5F_MAX_UNITS',
                 'Base Residential Density (#dwellings/acre)': 'BASE_DENS',
                 '1-Family Lot Frontage Requirement': '1F_FRONT',
                 '2-Family Lot Frontage Requirement': '2F_FRONT',
                 '3-Family Lot Frontage Requirement': '3F_FRONT',
                 '4-Family Lot Frontage Requirement': '4F_FRONT',
                 '5+-Family Lot Frontage Requirement': '5F_FRONT',
                 'PUD required with Subdivision': 'PUD_SUBDV',
                 'PUD Threshold #': 'PUD_THRESH',
                 'PUD allowed': 'PUD_ALLOW',
                 'PUD requiring land conservation': 'PUD_CONSERVE',
                 'Unique GIS schema identifier': 'GIS_ID'
}
    return [column_mapper.get(col, col) for col in columns]
